### ISSUE TITLE
jalv.gtk and jalv.gtk3 crashes with generic UI

### ISSUE THREAD

**Issue by sadko4u** [drobilla/jalv#33]
When loading tamgamp.lv2 generic interface, jalv.gtk and jalv.gtk3 crash with Segmentation fault.
jalv.qt4 and jalv.qt5 just work fine.
Here's the related issue: https://github.com/sadko4u/tamgamp.lv2/issues/5

Here's the backtrace:
```
0x000055555556170d in lv2_evbuf_get_size ()
(gdb) bt
#0  0x000055555556170d in lv2_evbuf_get_size ()
#1  0x0000555555561779 in lv2_evbuf_end ()
#2  0x000055555555e49f in jalv_apply_ui_events ()
#3  0x000055555555e8e2 in jalv_run ()
#4  0x00005555555641be in jack_process_cb ()
#5  0x00007ffff69ffa45 in Jack::JackClient::CallProcessCallback() (this=0x555555873400) at ../common/JackClient.cpp:620
#6  0x00007ffff69ffa45 in Jack::JackClient::ExecuteThread() (this=this@entry=0x555555873400) at ../common/JackClient.cpp:584
#7  0x00007ffff69ff1e8 in Jack::JackClient::Execute() (this=0x555555873400) at ../common/JackClient.cpp:569
#8  0x00007ffff6a17176 in Jack::JackPosixThread::ThreadHandler(void*) (arg=0x555555873638) at ../posix/JackPosixThread.cpp:59
#9  0x00007ffff7bc04f9 in start_thread () at /lib64/libpthread.so.0
#10 0x00007ffff4251eef in clone () at /lib64/libc.so.6
```

**Comment by drobilla** [comment]
Tolerated in 03aa65a
